name: Run Cucumber Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # Updated to latest version

      - name: Set up JDK 11
        uses: actions/setup-java@v4  # Updated to latest version
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Cache Maven Dependencies
        uses: actions/cache@v4  # Updated to latest version
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run Cucumber Tests
        run: mvn test

      - name: Upload Cucumber Reports
        if: always()
        uses: actions/upload-artifact@v4  # Updated to latest version
        with:
          name: cucumber-reports
          path: target/cucumber-reports/
